name: PR Title Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    branches:
      - main
  merge_group:

jobs:
  check-title:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: edp5/edp5-actions/pr-title-check@v1.5.1
